# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('characters', models.CharField(max_length=200)),
                ('judge', models.BooleanField(default=False)),
                ('remaining_characters', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='gamer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_tool.Room'),
        ),
    ]
