# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_tool', '0002_auto_20180211_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Player',
        ),
    ]
