# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tool', '0003_auto_20180211_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.CharField(max_length=30),
        ),
    ]
